### ISSUE TITLE
Inactive meetings: add the ability to list them

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#130]
This feature requirement is from the UK. There are many meetings which stopped running after the pandemic, but they might resume if seekers contact the organisers. 

These are the things that need to change to allow for that:

Admin side:
1.  New status of a meeting should be introduced: "Inactive"
So rather than a checkbox "published" / "unpublished", we should have a dropdown with 3 meeting statuses

2. It should be possible to add a meeting without start date or time when it runs. (only possible if you selected "inactive" status)

Seeker facing side:
1. In the list view inactive meetings should have a label "Contact organisers for timings" instead of day and time
<img width="452" alt="Screenshot 2023-04-08 at 09 02 53" src="https://user-images.githubusercontent.com/18451161/230708214-eac7c286-06c6-4695-8ba6-d703d1379587.png">

2. In the meeting panel itself, contacts should be clear and visible, so people can contact the organisers. 
We are requested to add a link to Meetup, FB group, Organiser's email
(I suggest we only allow these for inactive meetings to encourage them to submit emails)
Also, "Drop in" should be removed from the title, because it sounds like anyone can come, which is confusing, because seekers need to request those meetings.
<img width="471" alt="Screenshot 2023-04-08 at 09 40 24" src="https://user-images.githubusercontent.com/18451161/230709974-579ad701-db8a-4dc0-a4dd-2f3e883497b7.png">

**Comment by antontcymbal** [comment]
There are some styling issues with the current implementation:

1. Title is too wide, it should be constricted more to have more space around the "by request" label - this will make the label stand out more. 
2. Title should be "Beginners meditation class"
3. "Contact us for timings" - text styles are incorrect
4. Left align everything from "COntact us.." to meetup - facebook links
5. There should be more space above the description
6. Keep the registration panel


This is how it looks currently:
![WhatsApp Image 2023-04-12 at 16 32 58](https://user-images.githubusercontent.com/18451161/231497803-50dfa073-1963-461c-a70f-25ce629cb129.jpeg)


And this is the design:
<img width="305" alt="Screenshot 2023-04-12 at 16 33 12" src="https://user-images.githubusercontent.com/18451161/231497887-b334949c-2fc2-4577-9a25-276ea73ada55.png">

**Comment by antontcymbal** [comment]
small change: could you increase the font-weight of "email" and "phone" from 200 to 300. 

In this instance this is more important information than in an active meeting, and we should emphasize it a bit more - it is hard to see it with the font weight of 200

**Comment by antontcymbal** [comment]
Also, could you limit the width of the title on desktop as well, also to make the label appear more prominent

<img width="1238" alt="Screenshot 2023-04-12 at 17 58 08" src="https://user-images.githubusercontent.com/18451161/231514699-ade6b16b-92b2-4172-991f-64a10d76cc6c.png">

**Comment by Ardnived** [comment]
I've adjusted the title width and contact info font weight. But that will also change it for all other event types. But I think that ought to be fine.
