### ISSUE TITLE
Display upcoming meetings before their start date

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#131]
This is to encourage people to signup before the class starts. Perhaps we should display this a month before.
Here is how it could look in the list:

<img width="282" alt="Screenshot 2023-04-08 at 09 40 50" src="https://user-images.githubusercontent.com/18451161/230709835-274bbd24-f88a-4fea-90a5-dac3f52051e5.png">

**Comment by antontcymbal** [comment]
So the idea was to shorten the time to 1:15pm in this example to make it fit (and remove the time zone). 
Presumably the precise length of time is not as important for an upcoming meeting

**Comment by Ardnived** [comment]
I think this was implemented by @hrishi-verma . Can you verify @antontcymbal ?
