### ISSUE TITLE
Registration confirmation doesn't appear correctly

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#136]
After registering for an event, this is what I see:
![IMG_5240](https://user-images.githubusercontent.com/18451161/231192592-5d3c132f-e0af-4b63-a851-a08be960158f.PNG)

Three issues:

- "register now title" should disappear
- "register someone else" and "invite a friend along" are too close to each other
-  "register someone else" and "invite a friend along" are cut off at the bottom, and partially unaccessible:

https://user-images.githubusercontent.com/18451161/231193245-250d1c4b-2fa5-4791-9e7e-33751ff6e9b5.MP4

This is a link to that event:
https://wemeditate.com/map/f/event/158?back=%2310%2F51.494%2F-0.0712#16/51.477222/-0.016111

**Comment by Ardnived** [comment]
@antontcymbal The third issue is a duplicate of this: https://github.com/sydevs/Atlas/issues/134

The other issues are fixed and can be tested now.

**Comment by antontcymbal** [comment]
A couple of issues:

- "Thank you for registering" should be on two lines
- "Invite your friend along" is gray for some reason

![IMG_5247](https://user-images.githubusercontent.com/18451161/231486141-dc3bf72e-d41c-4b8a-95e3-55a54e7c275a.PNG)

**Comment by Ardnived** [comment]
Neither of these issues occur on my computer, but I've made some adjustments that might fix them.

**Comment by antontcymbal** [comment]
"Invite a friend along" is still gray, and it also doesn't do anything when you tap it.

**Comment by Ardnived** [comment]
The share button should work again now. But I don't have any way to know what's causing the greyed share url without being able to reproduce it. Try loading the page in an incognito window or another browser and see if you still get grey text.

**Comment by antontcymbal** [comment]
It's all good now, could you just push the "register someone else" and "invite a friend" buttons 30-40px lower, so there's more gap between them and the leaves?

![IMG_CB6551ABCE4A-1](https://user-images.githubusercontent.com/18451161/231527922-f855e17c-cfd9-46cb-9008-3e4a3f5ced19.jpeg)

**Comment by antontcymbal** [comment]
this works fine now
