### ISSUE TITLE
Technical fields appear when you add a city area

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#141]
Technical fields appear when you add a city area
This is bad because admins may start filling them out instead of using the search field at the top. They should be hidden (but accessible with a button I guess)

See here: 

<img width="807" alt="Screenshot 2023-04-12 at 18 38 59" src="https://user-images.githubusercontent.com/18451161/231524669-67b71cb7-063a-4c67-9a7f-0fa2e29f1b04.png">

**Comment by Ardnived** [comment]
I would say this is working as intended. The official boundaries will frequently not match up with our definition of what should included in a particular city's "area." Managers should be prompted to update these attributes after observing the map.
