### ISSUE TITLE
"City" doesn't get populated automatically when you search for an address of a venue

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#142]
"City" doesn't get populated automatically when you search for an address of a venue. 
So you have to expand the location fields and add it:

<img width="762" alt="Screenshot 2023-04-12 at 18 41 58" src="https://user-images.githubusercontent.com/18451161/231525525-949b2301-b3f7-4f97-bb74-3e29feb99a3e.png">

**Comment by Ardnived** [comment]
This is a failure of the data provided to us by Google. It's not clear that there is anything we can do about it.

**Comment by Ardnived** [comment]
@antontcymbal This should be fixed now thanks to @hrishi-verma . Could you check and verify it?
