### ISSUE TITLE
Fix displaying days of the week for weekly classes in the search view

### ISSUE THREAD

**Issue by anyaat** [sydevs/Atlas#144]
Days of the week are not displayed for weekly classes in the search view

![image](https://user-images.githubusercontent.com/16271474/232769443-21c98871-50f5-49ef-909a-bd906d14c47d.png)

**Comment by Ardnived** [comment]
@anyaat I can't seem to reproduce this issue. Can you check if it still occurs for you, and if so provide me a link that you are looking at + your browser and device type.

**Comment by anyaat** [comment]
@Ardnived indeed I could reproduce the bug only on Mac + Firefox and Windows + Chrome. Somehow on Mac + Chrome and Windows + Firefox the days of the week are displayed correctly.

Btw, I could not open the map page in Safari on both, my phone and laptop. I get the following result with [wemeditate.com/map](https://wemeditate.com/map) and with a [query option](https://wemeditate.com/map?q=London%2C%20Greater%20London%2C%20England%2C%20United%20Kingdom&latitude=51.507321899999994&longitude=-0.12764739999999997&type=place):
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/16271474/233157033-6ba2f1f7-e3c5-4c6a-a3ce-8473df501c99.png">

**Comment by Ardnived** [comment]
These issues appear to be fixed in the latest version.
