### ISSUE TITLE
Country admins can't access events

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#145]
Country admins in the UK can't access events created by other admins. This is the issue they see:

![WhatsApp Image 2023-04-13 at 12 25 43](https://user-images.githubusercontent.com/18451161/232886347-54ce1eba-dae6-4faa-921d-7c792238e58e.jpeg)

These are the events created by a global admin that they can't access:
![WhatsApp Image 2023-04-06 at 19 15 57](https://user-images.githubusercontent.com/18451161/232887865-2f99cd00-1cbc-4e32-93ea-d8ffd95582c8.jpeg)

**Comment by Ardnived** [comment]
@antontcymbal This should be fixed now
