### ISSUE TITLE
line break / carriage-return doesn't work

### ISSUE THREAD

**Issue by gennadiirumiantcev** [sydevs/Atlas#156]
There is the issue I encountered creating new event.
When formatting the description using carriage-return it would not appear in the final announcement.
<img width="553" alt="Screenshot 2023-08-18 at 11 20 20" src="https://github.com/sydevs/Atlas/assets/96073513/4bffafcd-2ebd-43c0-be00-ab1122d38355">
<img width="849" alt="Screenshot 2023-08-18 at 11 20 09" src="https://github.com/sydevs/Atlas/assets/96073513/5c8addaa-13b4-40d8-b775-f248ddc7f894">

**Comment by Ardnived** [comment]
This should be fixed now. Though may only recognise double line breaks, and not single line breaks (which is common for markdown).
