### ISSUE TITLE
Issue with images (mobile browser)

### ISSUE THREAD

**Issue by gennadiirumiantcev** [sydevs/Atlas#165]
Hi! I have found an issue with the display of images. When I open an event with more than one picture included, the second picture won't show, or even both(when Atlas is embedded on another website).
iOS iphone12mini 16.3 e iphone12 16.6 
I tested on iPad, worked fine

https://github.com/sydevs/Atlas/assets/96073513/2769ed09-96ca-4fe0-88af-458b325255f3

https://github.com/sydevs/Atlas/assets/96073513/f80abc48-fd6a-4125-9ea1-27dda37cc244

**Comment by Ardnived** [comment]
@gennadiirumiantcev This should be resolved now
