### ISSUE TITLE
Final pass before launch

### ISSUE THREAD

**Issue by antontcymbal** [sydevs/Atlas#48]
Map:

- [x] The new online / in person switch makes it very unclear on the phone that there's a list of classes: https://gyazo.com/6587a3cf07024926f9b12f9ab7a9aa31
Especially considering that you can only get to it if you scroll from the very bottom of the screen (otherwise you are moving the map)

  A good way to counter that would be to use this screen: https://projects.invisionapp.com/d/main?origin=v7#/console/16772232/347770641/preview?scrollOffset=3579
When you tap "show list", the list could smoothly scroll up. 

- [x] All in-person events have an "online" badge:
https://gyazo.com/e97ffa6ee0b57966c595d31eaea6935b

- [x] Fix the styling of the "online class" badge.
When the address and the badge don't fit into one line, the "online class" badge is too close to the previous line of text and it is not aligned to the left. Please make the margin at the top of the badge the same as between "online class" and "Saturdays..", and align it to the left when it doesn't fit on one line
https://gyazo.com/ea0f7b13ecd6274939ff9b8d854c8c64

- [ ] Tapping on a marker or circle doesn't do anything on iOS
https://gyazo.com/689b5436c4ecd9b4ea36b18a0d019805 
(in the above video I am tapping on a marker)
- [ ] Issues registering for a class on iOS because of grey area covering the registration field: https://gyazo.com/58dcf74ecf0e6142e178513c0fafd3eb
I can still scroll within the area that is not grey, but it looks broken
https://gyazo.com/d356fd80731f1306147eb6205e12ea19

CMS:

- [x] Make it so upon login a new person sees their dashboard, and not their "manager" page. It is confusing otherwise. 

- [x] Cannot save an event https://gyazo.com/4caa25d01f2d3a0a0096eee089824a73

- [x] Error when trying to create an event as a Birmingham manager: https://gyazo.com/9c86526868382db6078a5a1937912fa0

**Comment by Ardnived** [comment]
> Fix the styling of the "online class" badge.

This was caused because the badge was appearing where it wasn't supposed to. That is no longer the case, so hopefully it shouldn't occur again. It's not possible to change the styling when the length of the text changes because there is no way to know how the text has flowed.
